twbs/blog

_includes/footer.html

Fixes #11.
/cc @XhmikosR @cvrebert @patrickhlauke

Add RSS link in footer

---

_posts/2015-01-19-bootstrap-3-3-2-released.md

CC: @mdo @twbs/team @patrickhlauke

v3.3.2 post

---

_posts/2015-01-19-bootstrap-3-3-2-released.md

Add v3.3.2 CDN links

---

_posts/2015-03-16-bootstrap-3-3-4-released.md

~~Currently has some stubbiness. Will finish and rebase before merging/release.~~

v3.3.4 post

---

_posts/2015-06-15-bootstrap-3-3-5-released.md

CC: @twbs/team
Any comments on the proposed list of release highlights would be particularly appreciated.

Add v3.3.5 release post

---

_posts/2015-06-15-bootstrap-3-3-5-released.md

Per https://github.com/twbs/bootstrap/issues/16663#issuecomment-113673667
Refs https://github.com/twbs/bootstrap/pull/16359
CC: @twbs/team

Mention bower.json changes in v3.3.5 blog post

---

_posts/2015-06-15-bootstrap-3-3-5-released.md

Per https://github.com/twbs/bootstrap/issues/16663#issuecomment-113673667
Refs twbs/bootstrap#16663, twbs/bootstrap#16359
CC: @twbs/team

Add wiredep workaround to Bootstrap v3.3.5 post

---

_posts/2015-08-04-no-carrier.md

CC: @twbs/team for review
Also, my google-fu fails me when trying to search for '80 music videos based on their lyrics. So anyway, in the unlikely event that @mdo can't find something better, here are a couple possible video choices:
* Lake Koast Feat. Pretty Pretty & Malik - "Shut It Down": https://www.youtube.com/watch?v=xsH_kPUYOnE
* *The Closer* promo: https://www.youtube.com/watch?v=QLK_dIPe6V4

Add post about NO CARRIER

---

_posts/2015-11-24-bootstrap-3-3-6-released.md

v3.3.6 post

---

_posts/2015-11-24-bootstrap-3-3-6-released.md

To be merged when the v3.3.6 release is on the CDN.
/cc @jdorfman @cvrebert

Restore CDN links

---

_posts/2015-12-08-bootstrap-4-alpha-2.md

v4-alpha2 post

---

_config.yml
_includes/css/theme.css
_includes/header.html
_posts/2016-07-27-bootstrap-4-alpha-3.md
css/style.css

Along with the coming Alpha 3 blog post, I've made a few changes to the blog:
- Mentioned themes in the header since we communicate about that stuff there now.
- Update font stack to match Alpha 3's font change.
- Update config for Jekyll 3 setup (and fix CSS that broke from new highlighter).
- Alpha 3 blog post announcement (coming soon in a commit tomorrow).
/cc @twbs/team

Few tweaks and Alpha 3 blog post

---

_posts/2016-09-05-bootstrap-4-alpha-4.md

Stubbing this out for last minute release.

v4 Alpha 4 blog post

---

_posts/2016-09-05-bootstrap-4-alpha-4.md

Added code samples to 4.0.0-alpha.4 post

---

_posts/2016-09-05-bootstrap-4-alpha-5.md

Adding draft of Alpha 5 post

---

_posts/2017-10-19-bootstrap-4-beta-2.md

Remove apostrophe in it’s

---

_posts/2017-10-19-bootstrap-4-beta-2.md

Copyedit the Beta 2 post.

---

_posts/2017-12-28-bootstrap-4-beta-3.md

Beta 3 post

---

_includes/header.html

Matches Bootstrap 3 basic template:
https://getbootstrap.com/docs/3.3/getting-started/#template

Use latest version of html5shiv

---

_includes/header.html

to match analytics script loading on https://getbootstrap.com

optimised analytics (loads async)

---

_posts/2018-12-13-bootstrap-3-4-0.md

Stub out v3.4.0 post

---

_posts/2018-12-21-bootstrap-4-2-0.md
_posts/2018-12-21-bootstrap-4-2-1.md

First pass, needing images and more edits.

Start v4.2 post

---

_posts/2018-07-12-bootstrap-4-1-2.md
_posts/2018-07-24-bootstrap-4-1-3.md
_posts/2018-12-21-bootstrap-4-2-1.md

- Remove extra "to" in "Head to to the v4.1.x docs" in three files
- Change "Bootstrap will no feature" to "Bootstrap will not feature"

Fix small grammatical errors

---

_includes/header.html
_sass/_ads.scss
_sass/_style.scss
_sass/_theme.scss

Few small changes to button things up while I was writing the v4.3.0 post.

Design and CSS tweaks

---

_posts/2019-07-24-lts-plan.md

LTS plan post

---

_posts/2012-03-30-25000.md
_posts/2012-09-04-bootstrap-2-1-1-released.md
_posts/2012-10-30-2-2-1-hotfix-released.md
_posts/2013-02-07-bootstrap-2-3-released.md
_posts/2014-06-26-bootstrap-3-2-0-released.md
_posts/2014-09-23-bootlint.md
_posts/2014-10-29-bootstrap-3-3-0-released.md
_posts/2017-08-10-bootstrap-4-beta.md
_posts/2017-12-28-bootstrap-4-beta-3.md
_posts/2018-04-09-bootstrap-4-1.md
_posts/2019-02-11-bootstrap-4-3-0.md

This makes sure the internal links to posts exist.
Fixes #113

Make use of Jekyll's `post_url` filter.

---

_posts/2019-11-26-bootstrap-4-4-0.md

Add v4.4.0 blog post

---

.github/workflows/test.yml

If one of the following files changes, a new cache file will be generated
* Gemfile
* Gemfile.lock
* .github/workflows/test.yml
The results are crazy... From ~4min 30s down to ~30s

CI: add caching

---

_config.yml

Fixes https://github.com/twbs/blog/issues/127

Add open collective link

---

_config.yml

Ref. https://github.com/twbs/bootstrap/pull/30041

Change navbar GitHub link to org

---

_posts/2020-05-12-bootstrap-4-5-0.md

Add v4.5.0 post

---

_layouts/default.html

Remove the body_class from all pages

---

mdl-style.rb
src/_posts/2020-08-04-bootstrap-4-5-1.md

Add blog post for v4.5.1

---

src/_posts/2020-08-06-bootstrap-4-5-2.md

Add v4.5.2 post

---

src/_posts/2020-10-13-bootstrap-4-5-3.md

Drafting this ahead of the next release. @XhmikosR feel free to push any edits.
/cc @twbs/css-review

Add post for Bootstrap v4.5.3

---

_config.yml
src/_data/authors.yml
src/_layouts/default.html
src/_posts/2014-04-02-ratchet-2-0-2-released.md
src/_posts/2014-06-25-lmvtfy.md
src/_posts/2014-09-23-bootlint.md
src/_posts/2014-10-13-rorschach.md
src/_posts/2015-03-16-bootstrap-3-3-4-released.md
src/_posts/2015-06-15-bootstrap-3-3-5-released.md
src/_posts/2015-08-04-no-carrier.md
src/_posts/2016-07-25-bootstrap-3-3-7-released.md

Fixes #158 
Preview: <https://deploy-preview-162--bootstrapblog.netlify.app/>
Feed: <https://deploy-preview-162--bootstrapblog.netlify.app/feed.xml>

Attempt to fix authors

---

.github/workflows/ci.yml

* remove redundant CI env var; it's already set by the runner
* update docs and deploy only if we are on our repo

Clean up CI config

---

src/_posts/2021-01-19-bootstrap-icons-4.6.0.md

Add v4.6.0 post

---

.github/workflows/ci.yml
src/_posts/2021-01-19-bootstrap-4.6.0.md

~~Draft, I need to move the new posts to a `2021` folder + redirects~~ I'll do that later

Fix v4.6.0 post name

---

src/_includes/subnav.html
src/_sass/_style.scss

subnav: switch to font-weight: 600

---

src/_posts/2021/2021-02-10-bootstrap-5-beta-2.md

@XhmikosR  Just a small typo...

Fix broken link to "Background utilities".

---

_config.yml

Fixes #217 
---
Should we update docs assets, too? Probably need a small migration :)

Link to v5

---

src/_posts/2021/2021-06-17-bootstrap-5-0-2.md
src/_posts/2021/2021-06-22-bootstrap-5-0-2.md

Add v5.0.2 blog post

---

src/content/posts/2021/bootstrap-5-1-1.md

Add post for v5.1.1

---

src/content/posts/2021/bootstrap-5-1-2.md

v5.1.2 post

---

src/layouts/partials/scripts.html

@mdo: I don't think we are using Bootstrap's API anywhere (inline or elsewhere) so this should be OK, but please confirm too :)

Async load Bootstrap JS

---

config.yml
src/assets/scss/_footer.scss
src/layouts/partials/footer.html
src/layouts/partials/navbar.html

Remove Slack, fix Twitter link, add updated footer from docs

---

src/content/posts/2022/bootstrap-5-2-2.md

/cc @XhmikosR @julien-deramond @GeoSot

Add v5.2.2 post

---

src/layouts/_default/baseof.html
src/layouts/partials/head.html

* all JS files are loaded asynchronously now
* analytics is lower priority, no need to have them in `head`

Move JS script to head`and analytics to footer

---

src/layouts/_default/baseof.html
src/layouts/partials/head.html

Move analytics back to head

---

src/assets/js/color-modes.js
src/assets/scss/_navbar.scss
src/layouts/partials/navbar.html

- Revert modifications done in JS like upstream
- Get `--bs-dropdown-min-width` definition from upstream
- Get a11y enhancement from upstream

Fix theme toggle JavaScript and A11y

---

src/layouts/partials/scripts.html

Use `resources.Copy` instead of `targetPath`

scripts.html: simplify code

---

src/content/posts/2023/bootstrap-5-3-0-alpha3.md

/cc @XhmikosR This can be used for our changelog as well.

Add v5.3.0-alpha3 blog post

---

src/assets/js/color-modes.js

This PR gathers `color-modes.js` recent modifications from Bootstrap:
- https://github.com/twbs/bootstrap/commit/f0be063c9792f6fd123d933335efd0d8cc7f6f1f
- https://github.com/twbs/bootstrap/commit/ad9cb223a9899093e2537fdca6222e36465080a2

Improve color modes JS

---

src/assets/scss/style.scss
src/content/posts/2017/bootstrap-4-alpha-6.md
src/layouts/partials/scripts.html

Add extra params to handle custom page JS files
Preview: https://deploy-preview-389--bootstrapblog.netlify.app/2017/01/06/bootstrap-4-alpha-6/

Fix jsbin scripts

---

src/assets/js/color-modes.js

This PR simply applies the fix provided upstream in https://github.com/twbs/bootstrap/pull/39224

Fix edge case in `color-modes.js`

---

src/layouts/posts/single.html

Preview: https://deploy-preview-431--bootstrapblog.netlify.app/

single.html: add `mt-1` in related posts' `bi`

---

src/layouts/_default/baseof.html

Preview: https://deploy-preview-435--bootstrapblog.netlify.app/

baseof.html: switch to `site.Language.LanguageCode`

---

src/layouts/_default/rss.xml

Preview: https://deploy-preview-434--bootstrapblog.netlify.app/feed.xml
TODO:
- ~~[ ] Look into why author info doesn't show up (also on main)~~ EDIT: It's due to missing email address so it's normal

Update rss.xml from upstream

---

src/layouts/_default/rss.xml

Preview: https://deploy-preview-437--bootstrapblog.netlify.app/feed.xml

rss.xml: switch to summary

---

src/layouts/_default/home.html
src/layouts/partials/author-info.html
src/layouts/partials/banner.html

Preview: https://deploy-preview-440--bootstrapblog.netlify.app/

Lazyload banner only when not the first post

---

hugo.yml
src/layouts/_default/baseof.html
src/layouts/partials/social.html

Preview: https://deploy-preview-439--bootstrapblog.netlify.app/

social.html: include microdata template

---

package-lock.json
package.json
src/assets/js/lazyload.js

Preview: https://deploy-preview-446--bootstrapblog.netlify.app/

lazyload.js: import vanilla lazyload ESM build

---

src/layouts/partials/analytics.html
src/layouts/partials/head.html

Preview: https://deploy-preview-453--bootstrapblog.netlify.app/

head.html: include analytics only for production

---

src/layouts/partials/analytics.html

Preview: https://deploy-preview-454--bootstrapblog.netlify.app/

analytics.html: use async

---

src/layouts/_default/baseof.html
src/layouts/partials/head.html

We use defer for all JS so the requests are non-blocking
Preview: https://deploy-preview-449--bootstrapblog.netlify.app/

Move JavaScript to head

---

src/layouts/partials/head.html

Preview: https://deploy-preview-450--bootstrapblog.netlify.app/

preconnect: add crossorigin

---

src/content/posts/2023/bootstrap-5-3-0.md
src/content/posts/2023/bootstrap-5-3-2.md
src/content/posts/2023/bootstrap-icons-1-11-0.md

Preview: https://deploy-preview-457--bootstrapblog.netlify.app/

Fix 404 links and redirects

---

src/content/posts/2025/bootstrap-5-3-5.md

Going back to just add a quick post for this.

Add post for v5.3.5

---

src/content/posts/2025/bootstrap-icons-1-12-1-13.md

Fix Bootstrap Icons 1.13.1 link in May 09, 2025 blog post
