twbs/blog

- _includes/footer.html
- _includes/header.html
The ads and github buttons weren't loading on https since they're causing mixed content.
> use https to avoid mixed content

- _config.yml
`gems` config key has been defaulted to `plugins` since Jekyll 3.5, this PR intend to avoid the following deprecation warning at build time:
```
Deprecation: The 'gems' configuration option has been renamed to 'plugins'. Please update your config file accordingly.
```
> Plugins is the new gems

- _posts/2018-01-18-bootstrap-4.md
Updates these two empty links in the Bootstrap 4 blog post with my best guesses:
- Feather icons
- Media component -> Media object
> Add missing links to Bootstrap 4 blog post

- _includes/header.html
Safer (and sometimes faster as it saves a redirect) and the recommended way by Google.
> Always load Analytics over HTTPS

- _includes/header.html
The current template to compute classname assigned to the body tag is too long.
This PR proposes to use Liquid 4.0 Whitespace controller to improve template readability while maintaining current markup layout.
> Compact Liquid conditional to calculate body class

- _config.yml
- Remove config keys that *do not change* defaults set by Jekyll
- Improve overall readability:
- Move colons nearer to the "value" so that they do not appear disconnected from the key
(trailing whitespace to the key have no effect)
- Group *YAML lists* together
> Cleanup redundancy in configuration file

- _includes/video.html
Testing the nocookie domain. Should be more performant and disable tracking.
Ref. https://dri.es/how-to-remove-youtube-tracking
/CC @XhmikosR
> Disable youtube tracking

- _posts/2019-11-28-bootstrap-4-4-1.md
Blog post for 4.4.1 (release to fix https://github.com/twbs/bootstrap/issues/29743). @mdo, could you have a look if everything looks ok?
> Add 4.4.1 blog post

- _config.yml
- _layouts/default.html
I noticed the docs links were still pointing to the v4.4 docs/stylesheet. This should fix that.
> Update Bootstrap version references to v4.5.0

- _config.yml
The blog is using Bootstrap v4.5.2 CSS but the footer says 4.5.0 - updating here will fix that.
> Update Bootstrap current_version variable in config

- .github/workflows/ci.yml
This will make the upload-artifact action to error out instead of issuing a warning
> CI: add `if-no-files-found: error`

- src/_posts/2021/2021-01-19-bootstrap-4.6.0.md
- src/_posts/2021/2021-05-05-bootstrap-5.md
I'm not sure if you're taking PRs to the blog, but was reading the most recent v5 release post and noticed a small typo. Searched the repo and found one more occurrence that is fixed here.
Fixes typo `clases` to `classes` (two s's)
> Fix typo "clases" to "classes"

- .markdownlint.json
- src/assets/scss/style.scss
- src/content/posts/2016/bootstrap-4-alpha-3.md
- src/content/posts/2019/bootstrap-icons.md
- src/content/posts/2021/bootstrap-5-1-0.md
- src/content/posts/2021/bootstrap-icons-1-3-0.md
- src/content/posts/2021/bootstrap-icons-1-4-0.md
- src/content/posts/2021/bootstrap-icons-1-5-0.md
- src/content/posts/2021/bootstrap-icons-1-6-0.md
- src/content/posts/2021/bootstrap-icons-1-7-0.md
- src/content/posts/2022/bootstrap-icons-1-8-0.md
- src/layouts/_default/_markup/render-image.html
**Pros**
* consistency
* lazyload
* images have width/height automatically
**Cons**
* works only with Markdown syntax thus any raw HTML images will be broken; we could tweak the CSS changes I made to make this work for both, though
Note that we could probably change markdownlint config to disallow `img` tags if we want.
/CC @mdo @ffoodd WDYT?
> Use Hugo's render hook for images and lazyload them

- src/layouts/_default/home.html
- src/layouts/partials/banner.html
* lazyload banner image (not perfect if it's the first post, but it's a compromise we need to make)
* add dimensions (we should **always** add dimensions to prevent reflows)
> Improve banner partial

- package-lock.json
- package.json
It's a maintained fork.
@julien-deramond are you on macOS? If so, can you try this branch locally?
@GeoSot IIRC you are on Linux. Could you also try this branch locally?
I plan to switch everywhere to npm-rul-all2 later if all goes well.
> Replace npm-run-all with npm-run-all2

- hugo.yml
- src/layouts/partials/head.html
- src/layouts/partials/scripts.html
- src/layouts/partials/stylesheet.html
Preview: https://deploy-preview-424--bootstrapblog.netlify.app/
Ideally, we should use a sha256 for the hash since it's too long, but there's no way currently to trim this to say 7 characters.
> Fingerprint CSS and JS assets for cache busting

- package.json
- src/layouts/partials/scripts.html
- src/layouts/partials/stylesheet.html
Also, switch to defer for JS
Preview: https://deploy-preview-429--bootstrapblog.netlify.app/
> Minify files on production

- src/layouts/partials/navbar.html
Currently these links lack an accessible name at large screen sizes (as their actual text content is set in the `<small class="d-lg-none ...">`). Adding `aria-label` to the links themselves explicitly circumvents this problem.
Additionally, this fixes the visible text for the "Twitter" link.
Preview: https://deploy-preview-442--bootstrapblog.netlify.app/
> Add accessible name to navigation icon links

- src/layouts/partials/analytics.html
- src/layouts/partials/head.html
When running locally this project with `npm run start`, we can see the following warning that is a little bit disturbing:
```
WARN  Template partials/analytics.html is unused, source file /tmp/twbs/blog/src/layouts/partials/analytics.html
```
When not in production mode, the partial file is unused and generates the warning.
I'm aware that maybe we lose some readability with this version, so feel free to close this PR directly without any comments if you prefer to keep the previous version :)
* Locally, simply run `npm run start` and the warning is no more present. The `<script>` is not in the dev tools.
* In https://deploy-preview-465--bootstrapblog.netlify.app/, we can find the `<script>` in the dev tools.
> Prevent unused `partials/analytics.html` warning when not in production

- src/content/posts/2012/bootstrap-2-0-3-released.md
- src/content/posts/2013/bootstrap-3-released.md
- src/content/posts/2015/bootstrap-4-alpha.md
- src/content/posts/2017/bootstrap-4-beta-3.md
- src/content/posts/2017/bootstrap-4-beta.md
- src/content/posts/2021/bootstrap-4.6.0.md
- src/content/posts/2021/bootstrap-5-beta-2.md
- src/content/posts/2021/bootstrap-icons-1-3-0.md
- src/content/posts/2022/using-bootstrap-css-vars.md
- src/content/posts/2023/bootstrap-5-3-0-alpha2.md
Fix typos found via cSpell VS Code extension and CLI.
> Typo Fixes
